version: '2'

services:
  nginxproxy:
    container_name: nginxproxy
    image: jwilder/nginx-proxy
    restart: always
    environment:
      CLIENT_MAX_BODY_SIZE: 10240M
      GLOBAL_MAX_BODY_SIZE: 10240M
      ENABLE_IPV6: 1
    volumes:
     - /docker/nginxproxy/data/certs:/etc/nginx/certs
     - /docker/nginxproxy/config:/etc/nginx/conf.d
     - /docker/nginxproxy/data/dhparam:/etc/nginx/dhparam
     - /docker/nginxproxy/data/vhosts:/etc/nginx/vhost.d
     - /docker/nginxproxy/data/html:/usr/share/nginx/html
     - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
     - 80:80
     - 443:443


  nginxproxy_letsencrypt:
    container_name: letsencrypt
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    restart: always
    environment:
      DEFAULT_EMAIL: ${mail}
    volumes_from:
     - nginxproxy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
     - nginxproxy

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ${PW}
      POSTGRES_USER: guacamole_user
    image: postgres:11.5
    restart: always
    volumes:
    - /docker/guacamole/postgre/init:/docker-entrypoint-initdb.d:ro
    - /docker/guacamole/postgre/data:/var/lib/postgresql/data:rw

  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    restart: always
    volumes:
    - /docker/guacamole/guacd/drive:/drive:rw
    - /docker/guacamole/guacd/record:/record:rw

  guacamole:
    container_name: guacamole_compose
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${PW}
      POSTGRES_USER: guacamole_user   
      POSTGRES_DEFAULT_MAX_CONNECTIONS_PER_USER: 100
      VIRTUAL_HOST: ${sub}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${sub}
      LETSENCRYPT_MAIL: ${mail}
    image: guacamole/guacamole
    links:
    - guacd
    restart: always
    depends_on:
      - postgres
      - guacd
      - nginxproxy



